# Generated by Django 5.1.3 on 2024-12-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='moves',
            new_name='log_data',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='winner',
        ),
    ]
